### ISSUE TITLE
indexerror

### ISSUE THREAD

**Issue by yinyuhangi** [hiwad-aziz/kitti_deeplab#4]
When I ran the inference.py, the error was reported as follows:
IndexError: index 1002 is out of bounds for axis 1 with size 1002.
How to solve this problem?

**Comment by MukhlasAdib** [comment]
Please copy all of the error messages because the information you provided is not enough to make any conclusion

However, I got the similar issue. 
My problem is simple. The program, in helper.py, assumes a constant image size. This will lead to error when you give image with the wrong size as the input

You can solve this by simply insert the following lines in the first line of logits2image function in helper.py

```
width = logits.shape[1]
height = logits.shape[0]
```

So, the function code become

```
def logits2image(logits):
    width = logits.shape[1]
    height = logits.shape[0]
    logits = logits.astype(np.uint8)
    image = np.empty([height,width,3],dtype=float)
    ...
```
I hope this is the problem that you got.

**Comment by yinyuhangi** [comment]
OK, thank you very much.
